use std::ffi::OsString;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use clap::CommandFactory;
use clap_complete::env::EnvCompleter;

use crate::atomic_file::{self, PlannedDelete, PlannedWrite};
use crate::cli::{Cli, Shell};
use crate::error::{AvmError, Result};
use crate::profile::{self, BlockRemovalRequest, BlockRequest, ProfileFormat};
use crate::store::Store;

const COMPLETION_BLOCK_START: &str = "# >>> avm completion >>>";
const COMPLETION_BLOCK_END: &str = "# <<< avm completion <<<";
const MANAGED_HEADER: &str =
    "# Generated by AVM. Run `avm completion <shell> --install` to replace this file.\n";
const MAX_COMPLETION_BYTES: u64 = 1024 * 1024;
const POWERSHELL_REGISTRATION_TEMPLATE: &str = r#"
Register-ArgumentCompleter -Native -CommandName __AVM_COMMAND__ -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $relativeCursor = [Math]::Max(0, [Math]::Min($commandAst.Extent.Text.Length, $cursorPosition - $commandAst.Extent.StartOffset))
    $prefix = $commandAst.Extent.Text.Substring(0, $relativeCursor)
    $tokens = $null
    $parseErrors = $null
    $parsed = [System.Management.Automation.Language.Parser]::ParseInput($prefix, [ref]$tokens, [ref]$parseErrors)
    $parsedCommand = $parsed.Find({
        param($node)
        $node -is [System.Management.Automation.Language.CommandAst] -and $node.Extent.StartOffset -eq 0
    }, $true)
    if ($null -eq $parsedCommand) { return }

    $completionArgs = @()
    foreach ($element in $parsedCommand.CommandElements) {
        if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            $completionArgs += [string]$element.Value
        } else {
            $completionArgs += [string]$element.Extent.Text
        }
    }

    if ([string]::IsNullOrEmpty($wordToComplete)) {
        $nativeArgumentMode = Get-Variable -Name PSNativeCommandArgumentPassing -ValueOnly -ErrorAction SilentlyContinue
        $usesLegacyNativeArguments = $PSVersionTable.PSVersion -lt [Version]'7.3' -or $nativeArgumentMode -eq 'Legacy'
        if ($usesLegacyNativeArguments) {
            $completionArgs += '""'
        } else {
            $completionArgs += [string]::Empty
        }
    }

    $avmCommand = Get-Command -Name __AVM_COMPLETER__ -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $avmCommand) { return }
    $avmExecutable = $avmCommand.Source

    $previousComplete = $env:__AVM_ENV__
    try {
        $env:__AVM_ENV__ = 'powershell'
        $results = @(& $avmExecutable -- @completionArgs 2>$null)
    } finally {
        if ($null -eq $previousComplete) {
            Remove-Item Env:\__AVM_ENV__ -ErrorAction SilentlyContinue
        } else {
            $env:__AVM_ENV__ = $previousComplete
        }
    }

    foreach ($result in $results) {
        $split = ([string]$result) -split "`t", 2
        $value = $split[0]
        $help = if ($split.Length -eq 2) { $split[1] } else { $value }
        [System.Management.Automation.CompletionResult]::new($value, $value, 'ParameterValue', $help)
    }
}
"#;

pub(crate) struct SafePowershell;

impl EnvCompleter for SafePowershell {
    fn name(&self) -> &'static str {
        "powershell"
    }

    fn is(&self, name: &str) -> bool {
        matches!(name, "pwsh" | "powershell" | "powershell_ise")
    }

    fn write_registration(
        &self,
        var: &str,
        _name: &str,
        bin: &str,
        completer: &str,
        output: &mut dyn io::Write,
    ) -> io::Result<()> {
        write_safe_powershell_registration(var, bin, completer, output)
    }

    fn write_complete(
        &self,
        command: &mut clap::Command,
        arguments: Vec<OsString>,
        current_dir: Option<&Path>,
        output: &mut dyn io::Write,
    ) -> io::Result<()> {
        clap_complete::env::Powershell.write_complete(command, arguments, current_dir, output)
    }
}

pub(crate) fn complete_env() {
    use clap_complete::env::{Bash, Elvish, Fish, Shells, Zsh};

    let powershell = SafePowershell;
    let shells: [&dyn EnvCompleter; 5] = [&Bash, &Elvish, &Fish, &powershell, &Zsh];
    clap_complete::CompleteEnv::with_factory(Cli::command)
        .shells(Shells(&shells))
        .complete();
}

pub(crate) struct CompletionPlan {
    destination: PathBuf,
    file_update: Option<CompletionFileUpdate>,
    pub(crate) profile_requests: Vec<BlockRequest>,
}

pub(crate) struct CompletionCleanupPlan {
    deletes: Vec<PlannedDelete>,
    preserved: Vec<PathBuf>,
}

struct CompletionFileUpdate {
    write: PlannedWrite,
}

pub(crate) fn command(store: &Store, shell: Shell, install: bool, dry_run: bool) -> Result<()> {
    if !install {
        write_dynamic_completion(shell, &mut io::stdout())?;
        return Ok(());
    }

    let mut plan = plan_install(store, shell, true)?;
    let profile_updates = profile::plan_updates(plan.profile_requests.clone())?;
    if dry_run {
        println!("AVM completion installation preview for {shell}:");
        preview(&plan);
        println!("No files were changed.");
        return Ok(());
    }

    let _integration_lock = store.lock_state(false)?;
    plan.apply_file()?;
    profile::apply_updates(profile_updates)?;
    println!(
        "Installed {shell} completion at {}.",
        plan.destination.display()
    );
    if !plan.profile_requests.is_empty() {
        let profiles = plan
            .profile_requests
            .iter()
            .map(|request| request.path.display().to_string())
            .collect::<Vec<_>>()
            .join(", ");
        println!("Activated completion in {profiles}.");
    }
    Ok(())
}

pub(crate) fn plan_install(store: &Store, shell: Shell, activate: bool) -> Result<CompletionPlan> {
    let home = profile::home_dir()?;
    let powershell_profiles = if shell == Shell::Powershell && activate {
        profile::powershell_profiles()?
    } else {
        Vec::new()
    };
    plan_install_in(store, shell, &home, &powershell_profiles, activate)
}

pub(crate) fn activation_removal_requests() -> Result<Vec<BlockRemovalRequest>> {
    let home = profile::home_dir()?;
    let mut targets = vec![
        (home.join(".bashrc"), ProfileFormat::Utf8NoBom),
        (home.join(".zshrc"), ProfileFormat::Utf8NoBom),
    ];
    targets.extend(
        profile::powershell_profiles()?
            .into_iter()
            .map(|path| (path, ProfileFormat::PowerShell)),
    );
    targets.sort_by(|left, right| left.0.cmp(&right.0));
    targets.dedup_by(|left, right| left.0 == right.0);
    Ok(targets
        .into_iter()
        .map(|(path, format)| BlockRemovalRequest {
            path,
            markers: vec![(COMPLETION_BLOCK_START, COMPLETION_BLOCK_END)],
            format,
        })
        .collect())
}

pub(crate) fn plan_cleanup(store: &Store) -> Result<CompletionCleanupPlan> {
    let home = profile::home_dir()?;
    plan_cleanup_in(store, &home)
}

fn plan_cleanup_in(store: &Store, home: &Path) -> Result<CompletionCleanupPlan> {
    let mut paths = [Shell::Bash, Shell::Zsh, Shell::Fish, Shell::Powershell]
        .into_iter()
        .map(|shell| completion_path(store, shell, home))
        .collect::<Vec<_>>();
    paths.sort();
    paths.dedup();
    let mut deletes = Vec::new();
    let mut preserved = Vec::new();
    for path in paths {
        let metadata = match fs::symlink_metadata(&path) {
            Ok(metadata) => metadata,
            Err(error) if error.kind() == io::ErrorKind::NotFound => continue,
            Err(error) => {
                return Err(AvmError::io(format!("inspect {}", path.display()), error));
            }
        };
        if atomic_file::is_link_like(&metadata)
            || !metadata.is_file()
            || metadata.len() > MAX_COMPLETION_BYTES
        {
            preserved.push(path);
            continue;
        }
        let snapshot = atomic_file::read_snapshot(&path, MAX_COMPLETION_BYTES, "completion file")?;
        let Some(bytes) = snapshot.bytes() else {
            continue;
        };
        if bytes.starts_with(MANAGED_HEADER.as_bytes()) {
            deletes.push(PlannedDelete::new(
                path,
                snapshot,
                MAX_COMPLETION_BYTES,
                "completion file",
            ));
        } else {
            preserved.push(path);
        }
    }
    Ok(CompletionCleanupPlan { deletes, preserved })
}

pub(crate) fn preview_cleanup(plan: &CompletionCleanupPlan) {
    for delete in &plan.deletes {
        println!("Completion script: remove {}", delete.path().display());
    }
    for path in &plan.preserved {
        println!(
            "Completion script: preserve {} (not proven to be AVM-managed)",
            path.display()
        );
    }
}

pub(crate) fn preflight_cleanup(plan: &CompletionCleanupPlan) -> Result<()> {
    for delete in &plan.deletes {
        atomic_file::preflight_delete(delete)?;
    }
    Ok(())
}

pub(crate) fn apply_cleanup(plan: CompletionCleanupPlan) -> Result<usize> {
    let mut removed = 0;
    for delete in plan.deletes {
        removed += usize::from(atomic_file::apply_delete(delete)?);
    }
    Ok(removed)
}

fn plan_install_in(
    store: &Store,
    shell: Shell,
    home: &Path,
    powershell_profiles: &[PathBuf],
    activate: bool,
) -> Result<CompletionPlan> {
    let destination = completion_path(store, shell, home);
    let mut raw = Vec::new();
    write_registration(shell, &mut raw)?;
    let mut managed = MANAGED_HEADER.as_bytes().to_vec();
    managed.extend_from_slice(&raw);
    let file_update = plan_file_update(&destination, &managed, &raw)?;

    let profile_requests = if activate {
        match activation_command(shell, &destination) {
            Some(command) => activation_profiles(shell, home, powershell_profiles)
                .into_iter()
                .map(|path| BlockRequest {
                    path,
                    start: COMPLETION_BLOCK_START,
                    end: COMPLETION_BLOCK_END,
                    legacy_markers: Vec::new(),
                    command: command.clone(),
                    format: if shell == Shell::Powershell {
                        ProfileFormat::PowerShell
                    } else {
                        ProfileFormat::Utf8NoBom
                    },
                })
                .collect(),
            None => Vec::new(),
        }
    } else {
        Vec::new()
    };

    Ok(CompletionPlan {
        destination,
        file_update,
        profile_requests,
    })
}

pub(crate) fn preview(plan: &CompletionPlan) {
    println!("Completion script: {}", plan.destination.display());
    for request in &plan.profile_requests {
        println!("Completion profile: {}", request.path.display());
        println!("{}", request.start);
        println!("{}", request.command);
        println!("{}", request.end);
    }
}

impl CompletionPlan {
    pub(crate) fn destination(&self) -> &Path {
        &self.destination
    }

    pub(crate) fn apply_file(&mut self) -> Result<()> {
        if let Some(update) = self.file_update.take() {
            apply_file_update(update)?;
        }
        Ok(())
    }
}

fn write_dynamic_completion(shell: Shell, output: &mut dyn io::Write) -> Result<()> {
    output
        .write_all(MANAGED_HEADER.as_bytes())
        .map_err(|error| AvmError::io(format!("generate {shell} completion"), error))?;
    write_registration(shell, output)
}

fn write_registration(shell: Shell, output: &mut dyn io::Write) -> Result<()> {
    use clap_complete::env::{Bash, EnvCompleter, Fish, Zsh};

    if shell == Shell::Powershell {
        return SafePowershell
            .write_registration("COMPLETE", "avm", "avm", "avm", output)
            .map_err(|error| AvmError::io("generate powershell completion", error));
    }

    let completer: &dyn EnvCompleter = match shell {
        Shell::Bash => &Bash,
        Shell::Zsh => &Zsh,
        Shell::Fish => &Fish,
        Shell::Powershell => unreachable!("PowerShell registration is handled above"),
    };
    completer
        .write_registration("COMPLETE", "avm", "avm", "avm", output)
        .map_err(|error| AvmError::io(format!("generate {shell} completion"), error))
}

fn write_safe_powershell_registration(
    environment_variable: &str,
    command: &str,
    completer: &str,
    output: &mut dyn io::Write,
) -> io::Result<()> {
    let mut characters = environment_variable.chars();
    let valid_environment_variable = characters
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric());
    if !valid_environment_variable {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "completion environment variable is not a safe PowerShell identifier",
        ));
    }

    let template = POWERSHELL_REGISTRATION_TEMPLATE.replace("__AVM_ENV__", environment_variable);
    let (before_command, after_command) = template
        .split_once("__AVM_COMMAND__")
        .expect("PowerShell registration template has a command placeholder");
    let (before_completer, after_completer) = after_command
        .split_once("__AVM_COMPLETER__")
        .expect("PowerShell registration template has a completer placeholder");
    let registration = format!(
        "{before_command}{}{before_completer}{}{after_completer}",
        powershell_single_quote(command),
        powershell_single_quote(completer)
    );
    output.write_all(registration.as_bytes())
}

fn completion_path(store: &Store, shell: Shell, home: &Path) -> PathBuf {
    match shell {
        Shell::Bash => home
            .join(".local")
            .join("share")
            .join("bash-completion")
            .join("completions")
            .join("avm"),
        Shell::Zsh => home.join(".zsh").join("completions").join("_avm"),
        Shell::Fish => home
            .join(".config")
            .join("fish")
            .join("completions")
            .join("avm.fish"),
        Shell::Powershell => store.paths.root.join("completions").join("avm.ps1"),
    }
}

fn activation_profiles(shell: Shell, home: &Path, powershell_profiles: &[PathBuf]) -> Vec<PathBuf> {
    match shell {
        Shell::Bash => vec![home.join(".bashrc")],
        Shell::Zsh => vec![home.join(".zshrc")],
        Shell::Fish => Vec::new(),
        Shell::Powershell => powershell_profiles.to_vec(),
    }
}

fn activation_command(shell: Shell, destination: &Path) -> Option<String> {
    match shell {
        Shell::Bash => {
            let path = posix_single_quote(&destination.to_string_lossy().replace('\\', "/"));
            Some(format!("if [ -r {path} ]; then . {path}; fi"))
        }
        Shell::Zsh => {
            let path = posix_single_quote(&destination.to_string_lossy().replace('\\', "/"));
            Some(format!(
                "autoload -Uz compinit\n(( $+functions[compdef] )) || compinit\n\
                 if [[ -r {path} ]]; then source {path}; fi"
            ))
        }
        Shell::Fish => None,
        Shell::Powershell => {
            let path = powershell_single_quote(&destination.to_string_lossy());
            Some(format!(
                "$__avmCompletionScript = {path}\n\
                 try {{\n\
                     if (Test-Path -LiteralPath $__avmCompletionScript -PathType Leaf) {{\n\
                         . $__avmCompletionScript\n\
                     }}\n\
                 }} finally {{\n\
                     Remove-Variable -Name __avmCompletionScript -ErrorAction SilentlyContinue\n\
                 }}"
            ))
        }
    }
}

fn posix_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r#"'"'"'"#))
}

fn powershell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn plan_file_update(
    path: &Path,
    managed: &[u8],
    legacy_generated: &[u8],
) -> Result<Option<CompletionFileUpdate>> {
    let snapshot = atomic_file::read_snapshot(path, MAX_COMPLETION_BYTES, "completion file")?;
    let existing = snapshot.bytes().unwrap_or_default();
    if existing == managed {
        return Ok(None);
    }
    if !existing.is_empty()
        && existing != legacy_generated
        && !existing.starts_with(MANAGED_HEADER.as_bytes())
    {
        return Err(AvmError::Message(format!(
            "refusing to overwrite unowned completion file {}",
            path.display()
        )));
    }
    Ok(Some(CompletionFileUpdate {
        write: PlannedWrite::new(
            path.to_path_buf(),
            snapshot,
            managed.to_vec(),
            MAX_COMPLETION_BYTES,
            "completion file",
        ),
    }))
}

fn apply_file_update(update: CompletionFileUpdate) -> Result<()> {
    atomic_file::apply(update.write)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::platform::Platform;
    use crate::store::Paths;

    fn store(root: &Path) -> Store {
        Store::new(Paths::new(root.to_path_buf()), Platform::current().unwrap())
    }

    #[test]
    fn preserves_shell_completion_locations_and_uses_avm_home_for_powershell() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        assert_eq!(
            completion_path(&store, Shell::Zsh, &home),
            home.join(".zsh/completions/_avm")
        );
        assert_eq!(
            completion_path(&store, Shell::Fish, &home),
            home.join(".config/fish/completions/avm.fish")
        );
        assert_eq!(
            completion_path(&store, Shell::Powershell, &home),
            store.paths.root.join("completions/avm.ps1")
        );
    }

    #[test]
    fn plans_safe_powershell_activation_for_both_profiles() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join("it's avm"));
        let home = temporary.path().join("home");
        let profiles = vec![
            temporary.path().join("WindowsPowerShell/profile.ps1"),
            temporary.path().join("PowerShell/profile.ps1"),
        ];
        let plan = plan_install_in(&store, Shell::Powershell, &home, &profiles, true).unwrap();
        assert_eq!(plan.profile_requests.len(), 2);
        for request in plan.profile_requests {
            assert!(request.command.contains("Test-Path -LiteralPath"));
            assert!(request.command.contains("it''s avm"));
            assert!(!request.command.contains("Invoke-Expression"));
            assert_eq!(request.format, ProfileFormat::PowerShell);
        }

        let mut generated = Vec::new();
        write_dynamic_completion(Shell::Powershell, &mut generated).unwrap();
        let generated = String::from_utf8(generated).unwrap();
        assert!(!generated.contains("Invoke-Expression"));
        assert!(generated.contains("StringConstantExpressionAst"));
        assert!(generated.contains("& $avmExecutable -- @completionArgs"));
    }

    #[test]
    fn rejects_an_unowned_completion_file() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let path = completion_path(&store, Shell::Bash, &home);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "# user-owned\n").unwrap();
        assert!(plan_install_in(&store, Shell::Bash, &home, &[], false).is_err());
    }

    #[test]
    fn applies_completion_atomically_and_idempotently() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let mut first = plan_install_in(&store, Shell::Fish, &home, &[], false).unwrap();
        first.apply_file().unwrap();
        let second = plan_install_in(&store, Shell::Fish, &home, &[], false).unwrap();
        assert!(second.file_update.is_none());
        assert!(
            fs::read_to_string(second.destination)
                .unwrap()
                .contains(MANAGED_HEADER)
        );
    }

    #[test]
    fn completion_install_refuses_a_concurrent_destination_change() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let mut plan = plan_install_in(&store, Shell::Fish, &home, &[], false).unwrap();
        fs::create_dir_all(plan.destination.parent().unwrap()).unwrap();
        fs::write(&plan.destination, "# concurrent user file\n").unwrap();

        assert!(matches!(
            plan.apply_file(),
            Err(AvmError::ConcurrentFileChange { .. })
        ));
        assert_eq!(
            fs::read_to_string(plan.destination).unwrap(),
            "# concurrent user file\n"
        );
    }

    #[test]
    fn cleanup_removes_managed_completion_and_preserves_unowned_files() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let managed = completion_path(&store, Shell::Bash, &home);
        let unowned = completion_path(&store, Shell::Zsh, &home);
        fs::create_dir_all(managed.parent().unwrap()).unwrap();
        fs::create_dir_all(unowned.parent().unwrap()).unwrap();
        fs::write(&managed, format!("{MANAGED_HEADER}managed\n")).unwrap();
        fs::write(&unowned, "user owned\n").unwrap();

        let plan = plan_cleanup_in(&store, &home).unwrap();
        assert_eq!(plan.deletes.len(), 1);
        assert_eq!(plan.preserved, vec![unowned.clone()]);
        preflight_cleanup(&plan).unwrap();
        assert_eq!(apply_cleanup(plan).unwrap(), 1);
        assert!(!managed.exists());
        assert_eq!(fs::read_to_string(unowned).unwrap(), "user owned\n");
    }

    #[test]
    fn cleanup_preserves_unrelated_oversized_and_non_regular_paths() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let oversized = completion_path(&store, Shell::Bash, &home);
        let directory = completion_path(&store, Shell::Zsh, &home);
        fs::create_dir_all(oversized.parent().unwrap()).unwrap();
        fs::write(&oversized, vec![b'x'; MAX_COMPLETION_BYTES as usize + 1]).unwrap();
        fs::create_dir_all(&directory).unwrap();

        let plan = plan_cleanup_in(&store, &home).unwrap();
        assert!(plan.deletes.is_empty());
        assert!(plan.preserved.contains(&oversized));
        assert!(plan.preserved.contains(&directory));
    }

    #[cfg(unix)]
    #[test]
    fn cleanup_preserves_an_unrelated_symlinked_completion() {
        let temporary = tempfile::tempdir().unwrap();
        let store = store(&temporary.path().join(".avm"));
        let home = temporary.path().join("home");
        let completion = completion_path(&store, Shell::Fish, &home);
        let target = temporary.path().join("user-completion");
        fs::create_dir_all(completion.parent().unwrap()).unwrap();
        fs::write(&target, "user completion\n").unwrap();
        std::os::unix::fs::symlink(&target, &completion).unwrap();

        let plan = plan_cleanup_in(&store, &home).unwrap();
        assert!(plan.deletes.is_empty());
        assert!(plan.preserved.contains(&completion));
        assert_eq!(fs::read_to_string(target).unwrap(), "user completion\n");
    }
}
